Repository habx/ui-table, pull requests merged in 2020-06, with the labels that each got.

#331 Update index.ts
  src/index.ts
Labels: habx-autorelease

#332 APP-12162
  src/plugin/useExpandAll/index.ts
  src/plugin/useExpandAll/useExpandAll.interface.ts
  src/plugin/useExpandAll/useExpandAll.tsx
  src/types/Table.ts
  src/useTable/useTable.stories.tsx
Labels: habx-autorelease

#339 APP-12232 #automerge
  LICENSE
  README.md
Labels: habx-automerge

#345 APP-12303: stop propagation
  src/plugin/useRowSelect/useRowSelect.tsx
Labels: habx-automerge, habx-autorelease
