Repository habx/ui-table, pull requests merged in 2020-05, with the labels that each got.

#274 Update providerDecorator.js
  .storybook/providerDecorator.js
Labels: habx-automerge

#281 APP-11235: lib utils
  package-lock.json
  package.json
  src/cell/ArrayCell/ArrayCell.stories.tsx
  src/cell/ArrayCell/ArrayCell.tsx
  src/cell/ArrayCell/index.ts
  src/cell/BooleanCell/BooleanCell.stories.tsx
  src/cell/IconCell/IconCell.stories.tsx
  src/filter/SelectFilter.tsx
  src/filterFactory/selectFilterFactory.tsx
  src/filterMethod/arrayFilter.ts
  src/index.ts
  src/types/Table.ts
Labels: habx-autorelease

#284 APP-11256: fix ArrayCell
  src/cell/ArrayCell/ArrayCell.tsx
Labels: habx-automerge, habx-autorelease

#288 APP-11335: fix pagination
  package-lock.json
  package.json
  src/Table/Pagination.tsx
  src/filter/BooleanFilter.tsx
Labels: habx-automerge, habx-autorelease

#306 APP-11487: pageSizeOptions
  .storybook/main.js
  package-lock.json
  package.json
  src/Table/Pagination.tsx
  src/plugin/useControlledPagination/useControlledPagination.interface.ts
  src/useTable/useTable.stories.tsx
Labels: habx-automerge, habx-autorelease

#307 APP-10591: try to fix auto height
  src/Table/Table.style.ts
Labels: habx-automerge, habx-autorelease

#309 APP-10590: infinite scroll
  package-lock.json
  package.json
  src/Table/LoadingRow.tsx
  src/Table/Table.interface.ts
  src/Table/Table.tsx
  src/Table/TableRow.tsx
  src/Table/useVirtualize.ts
  src/plugin/useControlledFilters/index.ts
  src/plugin/useControlledPagination/index.ts
  src/plugin/useInfiniteScroll/index.ts
  src/plugin/useInfiniteScroll/useInfiniteScroll.interface.ts
  src/plugin/useInfiniteScroll/useInfiniteScroll.ts
  src/plugin/useInfiniteScroll/useInfiniteScrollErrors.ts
  src/types/Table.ts
  src/useTable/useTable.stories.tsx
Labels: habx-automerge
