Repository habx/ui-table, pull requests merged in 2020-10, with the labels that each got.

#534 APP-14627: change originalData to getOriginalData
  src/imex/imex.spec.ts
  src/imex/imex.stories.tsx
  src/imex/useExportTable.ts
  src/imex/useImportTable.tsx
Labels: habx-autorelease-major

#535 APP-14632: handle no data in xls
  src/imex/xls.utils.ts
Labels: habx-autorelease

#547 APP-14673 ui-table:Bad github URL in package.json
  package.json
Labels: habx-autorelease

#548 Syncing dev with v4.1.1
  package.json
Labels: habx-automerge

#568 APP-14961: add data-testids
  src/imex/useImportTable.tsx
Labels: habx-autorelease

#569 Syncing dev with v4.1.2
  src/imex/useImportTable.tsx
Labels: habx-automerge

#588 APP-15328: fix originalData mutation
  src/imex/useImportTable.tsx
Labels: habx-automerge, habx-autorelease

#605 feat: add .npmrc
  .npmrc
Labels: habx-automerge
